### ISSUE TITLE
Pagina ricerca

### ISSUE THREAD

**Issue by StefanoDeCapitani** [StefanoDeCapitani/boolbnb#20]
- Pagination degli appartamenti
- Aggiungere marker con icona customizzata [https://developer.tomtom.com/blog/build-different/use-searchmarkersmanager-add-custom-markers-map](https://github.com/StefanoDeCapitani/boolbnb/issues/url)
- Fare scroll degli appartamenti invece che tutta la pagina
- aggiungere link alla show dal titolo dell'appartamento

**Comment by andre-cyb** [comment]
![logo-marker-map](https://user-images.githubusercontent.com/85434706/155745598-1a9cac0d-a367-4ec2-9125-a19f49b1b773.png)

**Comment by andre-cyb** [comment]
@StefanoDeCapitani 
![marker-map2](https://user-images.githubusercontent.com/85434706/156006687-1e4ff761-1263-4812-8698-2ff60203a642.png)
